#! /bin/bash

. ~/.bash_profile

build

if [ "$1" == "production" ]; then
	node utilities/minify.js $(PWD)/public/scripts/final/fireflyDOMUpdates.js
fi

git add .

git commit -am "pre-pushed"

if [ $# -eq 1 ]; then

	git push --force $1

elif [ $# -eq 2 ]; then

	git push --force $1 $2":master"

fi